cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/404
tsc 404.ts
tsc 404.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/500
tsc 500.ts
tsc 500.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/chat
tsc chat.ts
tsc chat.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/login
tsc login.ts
tsc login.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/registration
tsc registration.ts
tsc registration.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/settings
tsc settings.ts
tsc settings.tmpl.ts
cd C:/OSPanel/domains/mf.messenger.praktikum.yandex/static/common
tsc validation.ts
tsc common.ts
tsc regExps.ts
TIMEOUT /T 100 
